export const cattleData = [
  {
    chip: "CH-2254-01",
    breed: "Brahman",
    birthDate: "2023-01-15",
    weight: "250",
    father: "Toro Max",
    mother: "Vaca Luna",
    disease: "Brucelosis",
    observations: "Sin observaciones.",
  },
  {
    chip: "CH-2254-02",
    breed: "Angus",
    birthDate: "2022-11-10",
    weight: "300",
    father: "Toro Rayo",
    mother: "Vaca Estrella",
    disease: "Ninguna",
    observations: "Revisar vacunación anual.",
  },
  {
    chip: "CH-2254-03",
    breed: "Holstein",
    birthDate: "2023-05-20",
    weight: "275",
    father: "Toro Nube",
    mother: "Vaca Flor",
    disease: "Fiebre aftosa",
    observations: "Tratamiento en curso.",
  },
  {
    chip: "CH-2254-04",
    breed: "Charolais",
    birthDate: "2022-08-08",
    weight: "320",
    father: "Toro León",
    mother: "Vaca Nieve",
    disease: "Ninguna",
    observations: "Animal tranquilo.",
  },
  {
    chip: "CH-2254-05",
    breed: "Hereford",
    birthDate: "2023-03-01",
    weight: "260",
    father: "Toro Bravo",
    mother: "Vaca Perla",
    disease: "Parásitos internos",
    observations: "Tratado con antiparasitario.",
  },
  {
    chip: "CH-2254-06",
    breed: "Simmental",
    birthDate: "2022-12-17",
    weight: "310",
    father: "Toro Fuego",
    mother: "Vaca Luna",
    disease: "Ninguna",
    observations: "Buen desarrollo.",
  },
  {
    chip: "CH-2254-07",
    breed: "Limousin",
    birthDate: "2023-02-25",
    weight: "240",
    father: "Toro Trueno",
    mother: "Vaca Sol",
    disease: "Dermatitis",
    observations: "Aplicar pomada.",
  },
  {
    chip: "CH-2254-08",
    breed: "Normando",
    birthDate: "2023-06-30",
    weight: "230",
    father: "Toro Eco",
    mother: "Vaca Roca",
    disease: "Ninguna",
    observations: "Nuevo en el hato.",
  },
  {
    chip: "CH-2254-09",
    breed: "Gyr",
    birthDate: "2022-09-12",
    weight: "290",
    father: "Toro Río",
    mother: "Vaca Nube",
    disease: "Brucelosis",
    observations: "Separado del grupo.",
  },
  {
    chip: "CH-2254-10",
    breed: "Brahman",
    birthDate: "2023-01-10",
    weight: "255",
    father: "Toro Max",
    mother: "Vaca Mar",
    disease: "Ninguna",
    observations: "Sin novedad.",
  },
  {
    chip: "CH-2254-11",
    breed: "Angus",
    birthDate: "2022-07-19",
    weight: "300",
    father: "Toro Rayo",
    mother: "Vaca Aurora",
    disease: "Mastitis",
    observations: "Bajo tratamiento.",
  },
  {
    chip: "CH-2254-12",
    breed: "Holstein",
    birthDate: "2023-04-22",
    weight: "265",
    father: "Toro Brío",
    mother: "Vaca Coral",
    disease: "Ninguna",
    observations: "Buena genética.",
  },
  {
    chip: "CH-2254-13",
    breed: "Charolais",
    birthDate: "2022-10-05",
    weight: "280",
    father: "Toro León",
    mother: "Vaca Blanca",
    disease: "Diarrea",
    observations: "En observación.",
  },
  {
    chip: "CH-2254-14",
    breed: "Hereford",
    birthDate: "2023-02-02",
    weight: "245",
    father: "Toro Bravo",
    mother: "Vaca Canela",
    disease: "Ninguna",
    observations: "Activo y fuerte.",
  },
  {
    chip: "CH-2254-15",
    breed: "Simmental",
    birthDate: "2022-06-28",
    weight: "330",
    father: "Toro Fuego",
    mother: "Vaca Grana",
    disease: "Fiebre aftosa",
    observations: "Recuperado.",
  },
  {
    chip: "CH-2254-16",
    breed: "Limousin",
    birthDate: "2023-03-30",
    weight: "270",
    father: "Toro Trueno",
    mother: "Vaca Nata",
    disease: "Ninguna",
    observations: "Buen comportamiento.",
  },
  {
    chip: "CH-2254-17",
    breed: "Normando",
    birthDate: "2023-07-05",
    weight: "250",
    father: "Toro Eco",
    mother: "Vaca Brisa",
    disease: "Dermatitis",
    observations: "Tratamiento diario.",
  },
  {
    chip: "CH-2254-18",
    breed: "Gyr",
    birthDate: "2022-11-23",
    weight: "295",
    father: "Toro Río",
    mother: "Vaca Arena",
    disease: "Ninguna",
    observations: "Vacunado recientemente.",
  },
  {
    chip: "CH-2254-19",
    breed: "Brahman",
    birthDate: "2023-01-28",
    weight: "260",
    father: "Toro Max",
    mother: "Vaca Sol",
    disease: "Brucelosis",
    observations: "Seguido por veterinario.",
  },
  {
    chip: "CH-2254-20",
    breed: "Angus",
    birthDate: "2023-05-11",
    weight: "240",
    father: "Toro Rayo",
    mother: "Vaca Alba",
    disease: "Parásitos",
    observations: "En tratamiento preventivo.",
  }
];

export function findCattleByChip(chipInput) {
  const chipLower = chipInput.toLowerCase();
  return cattleData.filter((cattle) =>
    cattle.chip.toLowerCase().includes(chipLower)
  );
}


export default {
  findCattleByChip,
};
  